name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Entra na pasta ui_tcc
        run: cd ui_tcc/

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email brunoalmeidadem@gmail.com
          git config --global user.name brunoalm
          git status
          git remote add origin https://${{secrets.token}}@github.com/brunoalm/brunoalm.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f